version: '3'

services:
  zigbee-gw:
    build: .
    container_name: zigbee-gw
    image: redkite/zigbee-gw:arm32v7
    restart: always
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./etc:/opt/zigbee-gw/etc
