zb_redirection_url: http://10.161.0.130:2001/sensors
zb_sources:
  0013a20041531c31:
    room: cave
    format: temperature;humidity
  0013a20041531ccf:
    room: kitchen
    format: temperature;humidity
  0013a20041502662:
    room: bedroom1
    format: temperature;humidity
  0013a2004172cf48:
    room: bedroom2
    format: temperature;humidity
  0013a200414f8f0c:
    room: office
    format: temperature;humidity
  0013a200415025db:
    room: outdoor
    format: temperature;humidity
serial:
  name: /dev/ttyUSB0
  speed: 9600
